# Generated by Django 3.1.2 on 2021-03-03 20:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(verbose_name='Ukedag')),
                ('start', models.TimeField(verbose_name='Starttid')),
                ('end', models.TimeField(verbose_name='Sluttid')),
                ('limit', models.IntegerField(verbose_name='Antallsbegrensing')),
                ('watchers', models.ManyToManyField(related_name='watches', to=settings.AUTH_USER_MODEL, verbose_name='Vaktansvarlige')),
            ],
        ),
    ]
