# Generated by Django 3.1.2 on 2021-04-21 19:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('watchlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftslot',
            name='limit',
        ),
        migrations.AlterField(
            model_name='shiftslot',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='watches', to=settings.AUTH_USER_MODEL, verbose_name='Vaktansvarlige'),
        ),
    ]
