# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-16 22:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Navn')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=8, verbose_name='Telefon')),
                ('study', models.CharField(max_length=255, verbose_name='Studieprogram')),
                ('year', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=(1, 1), verbose_name='Årstrinn')),
                ('group_choice', models.CharField(choices=[('DEVOPS', 'DEVOPS'), ('PR', 'PR'), ('LABOPS', 'LABOPS'), ('PROSJEKT', 'PROSJEKT')], max_length=255, verbose_name='Ønsket gruppe')),
                ('knowledge_of_hs', models.CharField(max_length=1000, verbose_name='Hvordan fikk du vite om Hackerspace?')),
                ('about', models.TextField(verbose_name='Litt om deg selv')),
                ('application_text', models.TextField(verbose_name='Hvorfor søker du hackerspace?')),
                ('application_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
