# Generated by Django 3.1.7 on 2022-01-19 20:23

import applications.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Navn')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=8, validators=[applications.validators.validate_phone_number], verbose_name='Telefon')),
                ('study', models.CharField(max_length=255, verbose_name='Studieprogram')),
                ('year', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=(1, 1), verbose_name='Årstrinn')),
                ('knowledge_of_hs', models.CharField(max_length=1000, verbose_name='Hvordan fikk du vite om Hackerspace?')),
                ('about', models.TextField(verbose_name='Litt om deg selv')),
                ('application_text', models.TextField(verbose_name='Hvorfor søker du hackerspace?')),
                ('application_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Gruppenavn')),
                ('text_main', models.TextField(verbose_name='Om gruppen generelt')),
                ('text_structure', models.TextField(blank=True, verbose_name='Om gruppens struktur')),
                ('text_workload', models.TextField(blank=True, verbose_name='Om gruppens arbeidsmengde')),
                ('project_group', models.BooleanField(default=False, verbose_name='Gruppen tilhører prosjektgruppen')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Navn')),
                ('period_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('period_end', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationGroupChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.application')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.applicationgroup')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='group_choice',
            field=models.ManyToManyField(through='applications.ApplicationGroupChoice', to='applications.ApplicationGroup'),
        ),
    ]
