# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-19 17:39
from __future__ import unicode_literals

import applications.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='group_choice',
            field=models.CharField(choices=[('DEVOPS', 'DEVOPS'), ('PR', 'PR'), ('LABOPS', 'LABOPS')], max_length=255, verbose_name='Ønsket gruppe'),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.CharField(max_length=8, validators=[applications.validators.validate_phone_number], verbose_name='Telefon'),
        ),
    ]
