# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-09 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20160919_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='group_choice',
            field=models.CharField(choices=[('DEVOPS', 'DEVOPS'), ('PR', 'PR'), ('LABOPS', 'LABOPS'), ('ER', 'ER')], max_length=255, verbose_name='Ønsket gruppe'),
        ),
    ]
