# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-31 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_auto_20180309_2251'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectApplication',
        ),
        migrations.AlterField(
            model_name='application',
            name='group_choice',
            field=models.CharField(choices=[('DEVOPS', 'DEVOPS'), ('PR', 'PR'), ('LABOPS', 'LABOPS'), ('ER', 'ER')], default=('DEVOPS', 'DEVOPS'), max_length=255, verbose_name='Ønsket gruppe'),
        ),
    ]
