# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-31 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_auto_20180731_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='group_choice',
            field=models.CharField(choices=[('DEVOPS', 'DevOps'), ('LABOPS', 'LabOps'), ('ARCADE', 'Prosjekt - Arkademaskin'), ('BOARDGAME', 'Prosjekt - Brettspill'), ('MOBILEGAME', 'Prosjekt - Mobilspill'), ('VIDEOGAME', 'Prosjekt - Videospill')], default=('DEVOPS', 'DevOps'), max_length=255, verbose_name='Ønsket gruppe'),
        ),
    ]
