# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-31 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_auto_20180731_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Gruppenavn')),
            ],
        ),
        migrations.RemoveField(
            model_name='application',
            name='group_choice',
        ),
        migrations.AddField(
            model_name='application',
            name='group_choice',
            field=models.ManyToManyField(related_name='groups', to='applications.Group'),
        ),
    ]
