# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-31 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    # Django 2.0 compat for renaming fields
    atomic = False

    dependencies = [
        ('applications', '0006_auto_20180731_1856'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='ApplicationGroup',
        ),
    ]
