# Generated by Django 2.0.10 on 2019-01-14 11:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_auto_20180731_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('period_end', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
