# Generated by Django 2.0.10 on 2019-01-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_applicationperiod_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationgroup',
            name='text_main',
            field=models.TextField(default='', verbose_name='Om gruppen generelt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationgroup',
            name='text_structure',
            field=models.TextField(default='', verbose_name='Om gruppens struktur'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationgroup',
            name='text_workload',
            field=models.TextField(default='', verbose_name='Om gruppens arbeidsmengde'),
            preserve_default=False,
        ),
    ]
