# Generated by Django 2.0.10 on 2019-01-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_auto_20190114_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationgroup',
            name='text_structure',
            field=models.TextField(blank=True, verbose_name='Om gruppens struktur'),
        ),
        migrations.AlterField(
            model_name='applicationgroup',
            name='text_workload',
            field=models.TextField(blank=True, verbose_name='Om gruppens arbeidsmengde'),
        ),
    ]
