# Generated by Django 2.0.10 on 2019-01-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_auto_20190114_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationgroup',
            name='project_group',
            field=models.BooleanField(default=False, verbose_name='Gruppen tilhører prosjektgruppen'),
        ),
    ]
