# Generated by Django 3.1.6 on 2021-04-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_auto_20210424_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='group_choice',
            field=models.ManyToManyField(through='applications.ApplicationGroupChoice', to='applications.ApplicationGroup'),
        ),
    ]
