# Generated by Django 3.2.13 on 2023-02-20 18:00

import applications.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_auto_20210424_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.CharField(max_length=20, validators=[applications.validators.validate_phone_number], verbose_name='Telefon'),
        ),
    ]
