# Generated by Django 3.2.16 on 2023-02-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_auto_20210424_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='project_interests',
            field=models.TextField(default='text', verbose_name='Hvilke prosjekter er du interessert i?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='group_choice',
            field=models.ManyToManyField(blank=True, through='applications.ApplicationGroupChoice', to='applications.ApplicationGroup'),
        ),
    ]
