# Generated by Django 3.2.16 on 2023-02-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0016_alter_application_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='project_interests',
            field=models.TextField(default='', verbose_name='Hvilke prosjekter er du interessert i?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='group_choice',
            field=models.ManyToManyField(blank=True, through='applications.ApplicationGroupChoice', to='applications.ApplicationGroup'),
        ),
    ]
