# Generated by Django 3.2.18 on 2023-09-16 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0018_alter_application_project_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationgroup',
            name='open_for_applications',
            field=models.BooleanField(default=True, verbose_name='Åpen for søknader'),
        ),
    ]
