# Generated by Django 3.2.18 on 2023-11-27 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0019_applicationgroup_open_for_applications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationgroupchoice',
            options={'ordering': ['priority']},
        ),
    ]
