services:
  website-old-db:
    image: postgres:13
    container_name: website-old-db
    env_file:
      - .env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "production"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    networks:
      - nginx_default
  website-old:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: website-old
    depends_on:
      website-old-db:
        condition: service_healthy
    volumes:
      - static:/app/static
      - media:/app/media
    restart: unless-stopped
    networks:
      - nginx_default

networks:
  nginx_default:
    external: true

volumes:
  static:
  media:
