# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-16 22:30
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('main_content', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('ingress_content', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publication date')),
                ('thumbnail', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('main_content', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('ingress_content', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publication date')),
                ('thumbnail', models.CharField(blank=True, max_length=200)),
                ('registration', models.BooleanField(default=False)),
                ('max_limit', models.PositiveIntegerField(blank=True, default=0)),
                ('registered_users', models.PositiveIntegerField(blank=True, default=0)),
                ('time_start', models.DateTimeField(verbose_name='Start time')),
                ('time_end', models.DateTimeField(verbose_name='End time')),
                ('place', models.CharField(blank=True, max_length=100, verbose_name='Place')),
                ('place_href', models.CharField(blank=True, max_length=200, verbose_name='Place URL')),
            ],
            options={
                'ordering': ('-time_start',),
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Filnavn')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tittel')),
                ('file', models.FileField(upload_to='uploads')),
                ('number', models.IntegerField(default=0)),
            ],
        ),
    ]
