# Generated by Django 3.1.7 on 2022-01-19 20:23

import ckeditor_uploader.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Tittel')),
                ('main_content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Hovedtekst')),
                ('ingress_content', models.TextField(blank=True, help_text='En kort introduksjon til teksten', max_length=400, validators=[django.core.validators.MaxLengthValidator(400)], verbose_name='Ingress')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publiseringsdato')),
                ('internal', models.BooleanField(default=False, verbose_name='Intern')),
                ('registration', models.BooleanField(default=False, verbose_name='Påmelding')),
                ('max_limit', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Maks påmeldte')),
                ('registration_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Påmeldingsstart')),
                ('registration_end', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Påmeldingsfrist')),
                ('deregistration_end', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Avmeldingsfrist')),
                ('external_registration', models.CharField(blank=True, default='', max_length=200, verbose_name='Lenke for ekstern påmelding')),
                ('time_start', models.DateTimeField(null=True, verbose_name='Starttidspunkt')),
                ('time_end', models.DateTimeField(null=True, verbose_name='Sluttidspunkt')),
                ('servering', models.BooleanField(default=False)),
                ('place', models.CharField(blank=True, max_length=100, verbose_name='Sted')),
                ('place_href', models.CharField(blank=True, max_length=200, verbose_name='Sted URL')),
                ('draft', models.BooleanField(default=False, verbose_name='Utkast')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible', to=settings.AUTH_USER_MODEL, verbose_name='Arrangementansvarlig')),
                ('thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.image')),
            ],
            options={
                'ordering': ('time_start',),
                'permissions': (('can_see_attendees', 'Can see attending, waitlist, register meetup in a event'), ('can_view_internal_event', 'Can see internal events')),
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Filnavn')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tittel')),
                ('file', models.FileField(blank=True, upload_to='event-uploads')),
                ('number', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='news.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registration time')),
                ('attended', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='news.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Tittel')),
                ('main_content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Brødtekst')),
                ('ingress_content', models.TextField(blank=True, help_text='En kort introduksjon til teksten', max_length=400, validators=[django.core.validators.MaxLengthValidator(400)], verbose_name='Ingress')),
                ('internal', models.BooleanField(default=False, verbose_name='Intern artikkel')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publication date')),
                ('redirect', models.IntegerField(default=0, verbose_name='Redirect')),
                ('draft', models.BooleanField(default=False, verbose_name='Utkast')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.image')),
            ],
            options={
                'ordering': ('-pub_date',),
                'permissions': (('can_view_internal_article', 'Can see internal articles'),),
            },
        ),
    ]
