# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-04 23:34
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('main_content', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('ingress_content', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('internal', models.BooleanField(default=False, verbose_name='Intern')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publication date')),
                ('thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.Image')),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Tittel')),
                ('main_content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Artikkel')),
                ('ingress_content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Ingress')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publiseringsdato')),
                ('internal', models.BooleanField(default=False, verbose_name='Intern')),
                ('registration', models.BooleanField(default=False, verbose_name='Påmelding')),
                ('max_limit', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Max påmeldte')),
                ('registration_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registrering start')),
                ('deregistration_end', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Avregistrering slutt')),
                ('time_start', models.DateTimeField(verbose_name='Start tidspunkt')),
                ('time_end', models.DateTimeField(verbose_name='Slutt tidspunkt')),
                ('place', models.CharField(blank=True, max_length=100, verbose_name='Sted')),
                ('place_href', models.CharField(blank=True, max_length=200, verbose_name='Sted URL')),
                ('thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.Image')),
            ],
            options={
                'ordering': ('-time_start',),
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registration time')),
                ('attended', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Filnavn')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tittel')),
                ('file', models.FileField(upload_to='uploads')),
                ('number', models.IntegerField(default=0)),
            ],
        ),
    ]
