# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-15 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='redirect',
            field=models.IntegerField(default=0, verbose_name='Redirect'),
        ),
    ]
