# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-03 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_article_related_thumb', to='files.Image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_event_related_thumb', to='files.Image'),
        ),
    ]
