# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-08 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_redirect'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='external_registration',
            field=models.CharField(default='', max_length=200, verbose_name='Ekstern påmelding url'),
        ),
    ]
