# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-07 23:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20160919_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registration opening date'),
        ),
    ]
