# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-02-13 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_event_external_registration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('time_start',)},
        ),
    ]
