# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-23 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20180213_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='external_registration',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Lenke for ekstern påmelding'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ingress_content',
            field=models.CharField(blank=True, max_length=30, verbose_name='Ingress'),
        ),
    ]
