# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-10 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_event_registration_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='registered_users',
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registration time'),
        ),
    ]
