# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-27 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20180723_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ingress_content',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ingress'),
        ),
    ]
