# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-17 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20161010_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='registration_datetime',
            new_name='registration_start',
        ),
        migrations.AddField(
            model_name='event',
            name='deregistration_end',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Deregistration closing date'),
        ),
    ]
