# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-18 01:37
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20161017_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='deregistration_end',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Avregistrering slutt'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ingress_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Ingress'),
        ),
        migrations.AlterField(
            model_name='event',
            name='main_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Artikkel'),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_limit',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Max påmeldte'),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sted'),
        ),
        migrations.AlterField(
            model_name='event',
            name='place_href',
            field=models.CharField(blank=True, max_length=200, verbose_name='Sted URL'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publiseringsdato'),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration',
            field=models.BooleanField(default=False, verbose_name='Påmelding'),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registrering start'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_end',
            field=models.DateTimeField(verbose_name='Slutt tidspunkt'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_start',
            field=models.DateTimeField(verbose_name='Start tidspunkt'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Tittel'),
        ),
    ]
