# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-27 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20180727_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ingress_content',
            field=models.CharField(blank=True, max_length=300, verbose_name='Ingress'),
        ),
    ]
