# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-30 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20161018_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='attended',
            field=models.BooleanField(default=False),
        ),
    ]
