# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-30 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20180727_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='ingress_content',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
