# Generated by Django 2.0.10 on 2019-04-30 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20190322_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('time_start',), 'permissions': (('can_create_event', 'Can edit event'), ('can_edit_event', 'Can edit event'), ('can_delete_event', 'Can delete an event'), ('can_see_attendees', 'Can see attending, waitlist, register meetup in a event'))},
        ),
    ]
