# Generated by Django 2.0.10 on 2019-05-06 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20190505_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='servering',
            field=models.BooleanField(default=False),
        ),
    ]
