# Generated by Django 2.0.10 on 2019-05-08 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20190508_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2019, 5, 8, 12, 2, 18, 907336), verbose_name='Sluttdato'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2019, 5, 8, 12, 2, 18, 907323), verbose_name='Startdato'),
        ),
        migrations.AlterField(
            model_name='event',
            name='hour_end',
            field=models.TimeField(default=datetime.datetime(2019, 5, 8, 12, 2, 18, 907355), verbose_name='Slutttidspunkt'),
        ),
        migrations.AlterField(
            model_name='event',
            name='hour_start',
            field=models.TimeField(default=datetime.datetime(2019, 5, 8, 12, 2, 18, 907345), verbose_name='Starttidspunkt'),
        ),
    ]
