# Generated by Django 2.0.10 on 2019-05-08 12:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_auto_20190508_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_end',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Sluttdato'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_start',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Startdato'),
        ),
        migrations.AlterField(
            model_name='event',
            name='hour_end',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Slutttidspunkt'),
        ),
        migrations.AlterField(
            model_name='event',
            name='hour_start',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Starttidspunkt'),
        ),
    ]
