# Generated by Django 2.0.10 on 2019-05-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_auto_20190508_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ingress_content',
            field=models.CharField(blank=True, help_text='En kort setning om hva artikkelen inneholder', max_length=300, verbose_name='Ingress'),
        ),
    ]
