# Generated by Django 2.0.10 on 2019-05-12 16:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_auto_20190508_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_end',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Påmelding slutt'),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Påmelding start'),
        ),
    ]
