# Generated by Django 2.0.10 on 2019-05-12 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0021_auto_20190512_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible', to=settings.AUTH_USER_MODEL, verbose_name='Arrangementansvarlig'),
        ),
        migrations.AddField(
            model_name='upload',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='news.Event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(upload_to='event-uploads'),
        ),
    ]
