# Generated by Django 3.0.2 on 2020-10-26 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0024_auto_20201012_1947'),
        ('news', '0024_auto_20201026_1701'),
    ]

    operations = [
    ]
