# Generated by Django 3.1.1 on 2021-01-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0026_article_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Utkast'),
        ),
    ]
