# Generated by Django 3.2.7 on 2021-09-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0041_auto_20210428_1823'),
        ('news', '0028_auto_20210210_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='skills',
            field=models.ManyToManyField(blank=True, to='userprofile.Skill', verbose_name='Ferdigheter'),
        ),
    ]
