# Generated by Django 3.2.7 on 2021-09-29 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0029_article_views'),
        ('news', '0029_event_skills'),
    ]

    operations = [
    ]
