# Generated by Django 3.2.12 on 2022-03-30 20:02

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0030_merge_0029_article_views_0029_event_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='main_content',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='main_content',
            field=markdownx.models.MarkdownxField(blank=True, verbose_name='Hovedtekst'),
        ),
    ]
