# Generated by Django 2.0.10 on 2019-01-14 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0003_image_thumb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('body', models.CharField(max_length=200)),
                ('thumbnail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.Image')),
            ],
        ),
    ]
