# Generated by Django 2.0.10 on 2019-05-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20190114_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100, verbose_name='Spørsmål')),
                ('text', models.TextField(max_length=200, verbose_name='Svar')),
                ('icon', models.CharField(help_text="Eksempel 'note_add' fra https://material.io/tools/icons/?style=baseline", max_length=30, verbose_name='Ikon')),
            ],
        ),
    ]
