# Generated by Django 2.0.10 on 2019-05-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_faqquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqquestion',
            name='text',
            field=models.TextField(max_length=1000, verbose_name='Svar'),
        ),
    ]
