# Generated by Django 3.1.2 on 2021-02-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20190508_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, help_text='Tekst som vises i banneret.', max_length=220, null=True, verbose_name='bannertext')),
                ('color', models.CharField(blank=True, help_text='Bakgrunnsfarge som en CSS-klasse. Dette kan være for eksempel hs-green, hs-yellow, hs-red, etc.', max_length=50, null=True, verbose_name='bannercolor')),
                ('active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('site', models.CharField(blank=True, help_text="Det interne navnet på URL-stien til siden som banneret skal dukke opp på. Wildcard (*) støttes. F.eks. er '*' ALLE sider, 'inventory.*' er alle lagersider.", max_length=250, null=True, verbose_name='bannersite')),
            ],
        ),
    ]
