# Generated by Django 3.1.2 on 2021-02-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='color',
            field=models.CharField(blank=True, help_text='Bakgrunnsfargen til banneret som en hex-farge. hs-green, hs-yellow og hs-red støttes også som presets.', max_length=50, null=True, verbose_name='bannercolor'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='text',
            field=models.TextField(blank=True, help_text='Tekst som vises i banneret.', max_length=1000, null=True, verbose_name='bannertext'),
        ),
    ]
