# Generated by Django 3.1.2 on 2021-02-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20210224_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='text_color',
            field=models.CharField(blank=True, help_text='Tekstfargen på banneret. hs-white og hs-black støttes som presets.', max_length=10, null=True, verbose_name='bannertextcolor'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='color',
            field=models.CharField(blank=True, help_text='Bakgrunnsfargen til banneret som en hex-farge. hs-green, hs-yellow og hs-red støttes også som presets.', max_length=10, null=True, verbose_name='bannercolor'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='site',
            field=models.CharField(blank=True, help_text="Det interne navnet på URL-stien til siden som banneret skal dukke opp på. Wildcard (*) støttes. F.eks. er '*' ALLE sider, 'inventory:*' er alle lagersider.", max_length=250, null=True, verbose_name='bannersite'),
        ),
    ]
