# Generated by Django 3.1.2 on 2021-02-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20210224_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='color',
            field=models.CharField(blank=True, default='hs-yellow', help_text='Bakgrunnsfargen til banneret som en hex-farge. hs-green, hs-yellow og hs-red støttes også som presets.', max_length=10, null=True, verbose_name='bannercolor'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='text_color',
            field=models.CharField(blank=True, default='hs-black', help_text='Tekstfargen på banneret. hs-white og hs-black støttes som presets.', max_length=10, null=True, verbose_name='bannertextcolor'),
        ),
    ]
