# Generated by Django 3.1.2 on 2021-03-22 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20210224_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, help_text='Banneret vil ikke vises uansett om den har aktiv status etter denne datoen.', null=True, verbose_name='sluttdato'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='site',
            field=models.CharField(blank=True, help_text="Det interne navnet på URL-stien til siden som banneret skal dukke opp på. Wildcard (*) støttes. F.eks. er '*' ALLE sider, 'inventory:*' er alle lagersider.", max_length=250, null=True, verbose_name='bannersider'),
        ),
    ]
