# Generated by Django 3.1.1 on 2021-04-12 19:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20210412_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
