# Generated by Django 3.1.1 on 2021-04-12 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_rule_thumb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='description',
        ),
    ]
