# Generated by Django 3.0.2 on 2021-04-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_rule_internal'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='printer_rule',
            field=models.BooleanField(default=False, verbose_name='Regel for bruk av printer'),
        ),
    ]
