# Generated by Django 3.1.1 on 2021-04-14 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_rule_printer_rule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rule',
            options={'permissions': (('can_view_internal_rule', 'Can view internal rule'),)},
        ),
    ]
