# Generated by Django 3.2.11 on 2022-02-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_auto_20210414_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='pub_date',
            field=models.DateField(auto_now=True, verbose_name='Publiseringsdato'),
        ),
    ]
