# Generated by Django 3.2.13 on 2022-11-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_rule_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='norwegian',
            field=models.BooleanField(default=True, verbose_name='Norsk regel'),
        ),
    ]
