# Generated by Django 5.0.3 on 2024-03-16 17:47

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_rule_norwegian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='body',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
