# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Textbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_text', models.CharField(max_length=100, verbose_name='Header')),
                ('header_fontsize', models.IntegerField(default=32, verbose_name='Fontsize')),
                ('header_color', models.CharField(default='#505050', help_text='RGB-code', max_length=7, verbose_name='Color')),
                ('header_fontfamily', models.CharField(default='sans-serif', max_length=100, verbose_name='Font family')),
                ('text_text', models.TextField(max_length=10000, verbose_name='Text')),
                ('text_columns', models.IntegerField(default=1, verbose_name='Columns')),
                ('text_fontsize', models.IntegerField(default=18, verbose_name='Fontsize')),
                ('text_color', models.CharField(default='#505050', help_text='RGB-code', max_length=7, verbose_name='Color')),
                ('text_fontfamily', models.CharField(default='sans-serif', max_length=100, verbose_name='Font family')),
                ('pub_date', models.DateTimeField(verbose_name='Publication date')),
            ],
            options={
                'verbose_name_plural': 'textboxes',
            },
        ),
    ]
