# Generated by Django 3.1.7 on 2022-01-19 20:29

import ckeditor_uploader.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Filnavn')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tittel')),
                ('file', models.FileField(blank=True, upload_to='event-uploads')),
                ('number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Projectarticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Tittel')),
                ('main_content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Brødtekst')),
                ('ingress_content', models.TextField(blank=True, help_text='En kort introduksjon til teksten', max_length=400, validators=[django.core.validators.MaxLengthValidator(400)], verbose_name='Ingress')),
                ('internal', models.BooleanField(default=False, verbose_name='Intern artikkel')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publication date')),
                ('redirect', models.IntegerField(default=0, verbose_name='Redirect')),
                ('draft', models.BooleanField(default=False, verbose_name='Utkast')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.image')),
            ],
            options={
                'ordering': ('-pub_date',),
                'permissions': (('can_view_internal_article', 'Can see internal articles'),),
            },
        ),
    ]
