# Generated by Django 3.2.12 on 2022-03-30 20:15

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('projectarchive', '0002_auto_20220127_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectarticle',
            name='main_content',
            field=markdownx.models.MarkdownxField(blank=True, verbose_name='Brødtekst'),
        ),
    ]
