# Generated by Django 2.0.8 on 2018-10-03 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='start_time',
        ),
    ]
