# Generated by Django 2.0.13 on 2019-03-11 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={},
        ),
        migrations.RenameField(
            model_name='queue',
            old_name='published',
            new_name='internal',
        ),
    ]
