# Generated by Django 2.2.6 on 2019-10-30 18:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='difficulty',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='queue',
            name='out_of_order',
            field=models.BooleanField(default=False),
        ),
    ]
