# Generated by Django 2.0.13 on 2019-04-21 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-start_date', '-start_time']},
        ),
    ]
