# Generated by Django 2.2.1 on 2019-05-19 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_image_compressed'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='files.Image'),
            preserve_default=False,
        ),
    ]
