# Generated by Django 2.0.8 on 2018-11-14 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20181003_2054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queue',
            options={'verbose_name': 'kø', 'verbose_name_plural': 'køer'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'reservasjon', 'verbose_name_plural': 'reservasjoner'},
        ),
        migrations.AlterField(
            model_name='queue',
            name='description',
            field=models.TextField(default='', max_length=512, verbose_name='beskrivelse'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='navn'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='published',
            field=models.BooleanField(default=False, verbose_name='publisert'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(verbose_name='dato'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_time',
            field=models.TimeField(verbose_name='sluttidspunkt'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='parent_queue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations.Queue', verbose_name='foreldrekø'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_time',
            field=models.TimeField(verbose_name='starttidspunkt'),
        ),
    ]
