# Generated by Django 2.2.6 on 2019-10-30 18:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20191030_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='difficulty',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
