# Generated by Django 2.0.13 on 2019-03-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20190311_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='queue',
            name='internal',
            field=models.BooleanField(default=False, verbose_name='intern'),
        ),
    ]
