# Generated by Django 2.0.9 on 2018-11-14 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20181114_1906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'permissions': (('view_name', 'View name of reservee'),), 'verbose_name': 'reservasjon', 'verbose_name_plural': 'reservasjoner'},
        ),
    ]
