# Generated by Django 3.0.2 on 2020-02-05 20:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20191030_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='difficulty',
            field=models.PositiveSmallIntegerField(default=3, help_text='Velg et tall mellom 1-5, der 1 er lettest', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
