# Generated by Django 2.2.1 on 2019-05-19 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_auto_20190519_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='end_time',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='start_time',
            new_name='start',
        ),
    ]
