# Generated by Django 2.2.1 on 2019-05-19 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_auto_20190519_1219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'permissions': [('view_user_details', 'Can view full name and phone number on reservation view')]},
        ),
    ]
