# Generated by Django 3.1.7 on 2022-01-19 20:23

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='committees', verbose_name='miniatyrbilde')),
                ('description', models.TextField(verbose_name='beskrivelse')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('active', models.BooleanField()),
                ('priority', models.IntegerField(default=0)),
                ('economy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Økonomiansvarlig', to=settings.AUTH_USER_MODEL)),
                ('main_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Leder', to=settings.AUTH_USER_MODEL)),
                ('second_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Nestleder', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
