# Generated by Django 2.0.10 on 2019-03-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0003_auto_20190307_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
