# Generated by Django 2.0.10 on 2019-03-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0004_committee_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='committee',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='committees', verbose_name='miniatyrbilde'),
        ),
    ]
