# Generated by Django 3.0.2 on 2020-10-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0005_auto_20190307_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
