# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 22:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('inventory', '0001_initial'), ('inventory', '0002_auto_20171121_2043'), ('inventory', '0002_auto_20171107_2108'), ('inventory', '0003_merge'), ('inventory', '0004_auto_20180324_1957'), ('inventory', '0005_auto_20180329_1659'), ('inventory', '0006_auto_20180329_1757'), ('inventory', '0007_auto_20180329_1757'), ('inventory', '0008_auto_20180329_1828'), ('inventory', '0009_auto_20180329_1922'), ('inventory', '0010_auto_20180329_1931'), ('inventory', '0011_auto_20180329_1933'), ('inventory', '0012_auto_20180329_1933'), ('inventory', '0013_auto_20180329_1933'), ('inventory', '0014_auto_20180330_0147')]

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('quantity', models.IntegerField(default=1)),
                ('visible', models.BooleanField(default=True)),
                ('zone', models.CharField(max_length=50, null=True)),
                ('shelf', models.IntegerField(null=True)),
                ('place', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=300)),
                ('visible', models.BooleanField(default=True)),
                ('loan_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_lent')),
                ('return_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='return_date')),
                ('date_returned', models.DateTimeField(null=True, verbose_name='date_returned')),
                ('borrower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_set', to=settings.AUTH_USER_MODEL)),
                ('lender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lender_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('parent_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_tags', to='inventory.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(to='inventory.Tag'),
        ),
        migrations.AddField(
            model_name='item',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.Image'),
        ),
        migrations.AddField(
            model_name='item',
            name='column',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='row',
            field=models.IntegerField(null=True),
        ),
        migrations.RemoveField(
            model_name='item',
            name='place',
        ),
        migrations.AddField(
            model_name='item',
            name='column',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='row',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='inventory.Item'),
        ),
        migrations.AddField(
            model_name='loan',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='loan',
            name='borrower',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='email',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='phone',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
