# Generated by Django 3.1.2 on 2020-10-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='', verbose_name='Bilde'),
            preserve_default=False,
        ),
    ]
