# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-30 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_squashed_0014_auto_20180330_0147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='borrower',
        ),
    ]
