# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-30 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_loan_borrower'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='borrower',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
