# Generated by Django 3.1.2 on 2020-10-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20201020_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Beskrivelse'),
        ),
    ]
