# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-02-13 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20171121_2043'),
        ('inventory', '0002_auto_20171107_2108'),
    ]

    operations = [
    ]
