# Generated by Django 3.1.2 on 2020-10-20 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20201020_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, max_length=200, verbose_name='Beskrivelse'),
        ),
    ]
