# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-29 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20180324_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Item'),
        ),
        migrations.AddField(
            model_name='loan',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
