# Generated by Django 3.1.2 on 2020-10-20 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20201020_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Detaljsidevisninger'),
        ),
    ]
