# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-29 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20180329_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='email',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='phone',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
