# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-29 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20180329_1828'),
    ]

    operations = [
    ]
