# Generated by Django 3.1.2 on 2020-10-21 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20201021_0211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='thumbnail',
        ),
    ]
