# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-29 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20180329_1922'),
    ]

    operations = [
    ]
