# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-29 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20180329_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='inventory.Item'),
        ),
    ]
