# Generated by Django 3.0.2 on 2020-11-02 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20201026_1701'),
        ('inventory', '0013_auto_20201026_1754'),
    ]

    operations = [
    ]
