# Generated by Django 3.1.2 on 2020-10-31 14:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0013_auto_20201026_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Antall')),
                ('loan_from', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Utlånt fra')),
                ('loan_to', models.DateField(verbose_name='Utlånt til')),
                ('purpose', models.CharField(max_length=50, verbose_name='Formål')),
                ('contact_name', models.CharField(max_length=100, verbose_name='Utlåners navn')),
                ('contact_phone', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$', message='Skriv inn et gyldig telefonnummer')], verbose_name='Utlåners tlf.')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Utlåners epost')),
                ('consent', models.BooleanField(validators=[inventory.models.validate_consent], verbose_name='Datalagringssamtykke')),
                ('returned', models.BooleanField(default=False, verbose_name='Levert tilbake?')),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Godkjenner')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item', verbose_name='Lånegjenstand')),
            ],
        ),
    ]
