# Generated by Django 3.1.2 on 2020-11-02 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0014_itemloan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemloan',
            name='returned',
        ),
        migrations.AddField(
            model_name='itemloan',
            name='returned_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tilbakelevert på dato'),
        ),
        migrations.AlterField(
            model_name='itemloan',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Godkjenner'),
        ),
    ]
