# Generated by Django 3.1.2 on 2020-11-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auto_20201102_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemloan',
            name='returned_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Tilbakelevert på dato'),
        ),
    ]
