# Generated by Django 3.1.1 on 2021-01-27 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auto_20201116_1917'),
        ('inventory', '0018_auto_20201110_1913'),
    ]

    operations = [
    ]
