# Generated by Django 3.2.8 on 2021-10-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_item_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.CharField(blank=True, max_length=50, verbose_name='Hylleplass'),
        ),
    ]
