# Generated by Django 3.1.1 on 2021-11-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_alter_item_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unknown_stock',
            field=models.BooleanField(blank=True, null=True, verbose_name='Ukjent lagerbeholdning'),
        ),
    ]
