# Generated by Django 3.1.1 on 2021-11-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_item_unknown_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unknown_stock',
            field=models.BooleanField(null=True, verbose_name='Ukjent lagerbeholdning'),
        ),
    ]
