# Generated by Django 3.1.1 on 2021-11-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_auto_20211111_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unknown_stock',
            field=models.BooleanField(default=False, verbose_name='Ukjent lagerbeholdning'),
        ),
    ]
