# Generated by Django 3.1.1 on 2021-11-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_auto_20211111_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='can_loan',
            field=models.BooleanField(default=True, verbose_name='Kan lånes'),
        ),
        migrations.AddField(
            model_name='item',
            name='max_loan_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Maks lånetid'),
        ),
    ]
