# Generated by Django 3.1.1 on 2021-11-17 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_auto_20211117_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='max_loan_time',
        ),
    ]
