# Generated by Django 3.2.13 on 2022-11-09 17:51

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_item_max_loan_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Navn')),
                ('description', markdownx.models.MarkdownxField(blank=True, verbose_name='Beskrivelse')),
                ('inventory_link', models.URLField(blank=True, null=True, verbose_name='Lenke til lagersystemet')),
            ],
        ),
    ]
