# Generated by Django 3.2.13 on 2023-02-20 18:00

import applications.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_item_max_loan_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemloan',
            name='contact_phone',
            field=models.CharField(max_length=20, validators=[applications.validators.validate_phone_number], verbose_name='Utlåners tlf.'),
        ),
    ]
