# Generated by Django 3.2.18 on 2023-02-25 12:02

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0012_auto_20210210_1725'),
        ('inventory', '0028_alter_itemloan_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name', models.CharField(max_length=255, verbose_name='Navn')),
                ('description', markdownx.models.MarkdownxField(blank=True, verbose_name='Beskrivelse')),
                ('inventory_link', models.URLField(blank=True, null=True, verbose_name='Lenke til lagersystemet')),
                ('thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.image', verbose_name='Bilde')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
