# Generated by Django 3.2.13 on 2023-02-20 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemloan',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.itemloan', verbose_name='Lånegjenstand'),
        ),
    ]
