# Generated by Django 5.0.3 on 2024-03-16 17:47

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, verbose_name='Beskrivelse'),
        ),
    ]
