# Generated by Django 3.2.18 on 2024-02-28 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemloan',
            name='loan_from',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Lån fra'),
        ),
    ]
