# Generated by Django 5.0.3 on 2024-04-10 20:32

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_alter_itemloan_loan_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, verbose_name='Beskrivelse'),
        ),
    ]
