# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-29 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userauthentication',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserAuthentication',
        ),
    ]
