# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-02-06 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koohii', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeestatus',
            name='status',
        ),
    ]
