# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-02-06 19:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koohii', '0002_remove_coffeestatus_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoffeeStatus',
            new_name='CoffeePot',
        ),
    ]
