# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-02-06 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koohii', '0003_auto_20180206_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coffeepot',
            options={'verbose_name_plural': 'Coffee Pots'},
        ),
        migrations.RemoveField(
            model_name='opendata',
            name='closed',
        ),
        migrations.AlterField(
            model_name='coffeepot',
            name='datetime',
            field=models.DateTimeField(blank=True),
        ),
    ]
