# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-02-06 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koohii', '0004_auto_20180206_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeepot',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
