# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-14 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Mandag', 'Mandag'), ('Tirsdag', 'Tirsdag'), ('Onsdag', 'Onsdag'), ('Torsdag', 'Torsdag'), ('Fredag', 'Fredag')], default='Mandag', max_length=7)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('icon', models.ImageField(upload_to='skillicons')),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='auto_duty',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='auto_name',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='website/static/img/profilepictures/default.jpg', upload_to='website/static/img/profilepictures'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='study',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='duty',
            field=models.ManyToManyField(blank=True, related_name='duty', to='userprofile.DutyTime'),
        ),
        migrations.AddField(
            model_name='profile',
            name='group',
            field=models.ManyToManyField(blank=True, related_name='groups', to='userprofile.Group'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='skills', to='userprofile.Skill'),
        ),
    ]
