# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-14 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20171114_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profilepictures/default.jpg', upload_to='profilepictures'),
        ),
    ]
