# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-15 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20171114_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.ImageField(blank=True, upload_to='skillicons'),
        ),
    ]
