# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-21 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20171115_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='group',
            field=models.ManyToManyField(blank=True, related_name='profile', to='userprofile.Group'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profilepictures/default.png', upload_to='profilepictures'),
        ),
    ]
