# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-23 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_auto_20180323_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tos_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
