# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-11 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_auto_20180323_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='profilepictures', verbose_name='Profilbilde'),
        ),
    ]
