# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-23 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_profile_tos_accepted'),
        ('userprofile', '0008_auto_20180411_1314'),
    ]

    operations = [
    ]
