# Generated by Django 2.0.10 on 2019-01-29 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_merge_20180623_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='auto_duty',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='duty',
        ),
        migrations.DeleteModel(
            name='DutyTime',
        ),
    ]
