# Generated by Django 2.0.10 on 2019-03-21 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0010_auto_20190129_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='group',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
