# Generated by Django 2.0.10 on 2019-04-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0013_auto_20190408_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='social_slack',
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_battlenet',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Battle.net-tag'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_git',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Git navn'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_steam',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Steam navn'),
        ),
    ]
