# Generated by Django 2.0.10 on 2019-05-05 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0014_auto_20190430_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allergi_annet',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Oppgi evt. annet ønske vedrørende arrangementer med matservering.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='allergi_gluten',
            field=models.BooleanField(default=False, verbose_name='Ønsker glutenfritt alternativ i arrangementer med matservering'),
        ),
        migrations.AddField(
            model_name='profile',
            name='allergi_vegan',
            field=models.BooleanField(default=False, verbose_name='Ønsker vegansk alternativ i arrangementer med matservering'),
        ),
        migrations.AddField(
            model_name='profile',
            name='allergi_vegetar',
            field=models.BooleanField(default=False, verbose_name='Ønsker vegetar alternativ i arrangementer med matservering'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_email',
            field=models.BooleanField(default=False, verbose_name='Vis e-postadresse i din profil'),
        ),
    ]
