# Generated by Django 2.0.10 on 2019-05-06 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0015_auto_20190505_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='allergi_annet',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Evt. andre ønsker for matservering.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='allergi_gluten',
            field=models.BooleanField(default=False, verbose_name='Ønsker glutenfritt alternativ'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='allergi_vegan',
            field=models.BooleanField(default=False, verbose_name='Ønsker vegansk alternativ'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='allergi_vegetar',
            field=models.BooleanField(default=False, verbose_name='Ønsker vegetar alternativ'),
        ),
    ]
