# Generated by Django 2.0.10 on 2019-05-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0016_auto_20190506_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='social_git',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Github brukernavn'),
        ),
    ]
