# Generated by Django 2.0.10 on 2019-05-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0017_auto_20190506_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='limit_social',
            field=models.BooleanField(default=False, verbose_name='Vis sosiale profiler kun for andre Hackerspace-medlemmer'),
        ),
    ]
