# Generated by Django 2.0.10 on 2019-05-06 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0018_profile_limit_social'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('can_view_social', 'Can see social fields on UserProfile'),)},
        ),
    ]
