# Generated by Django 2.0.10 on 2019-05-07 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0019_auto_20190506_1935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('can_view_social', 'Can see social fields on UserProfile'), ('can_view_admin', 'Can see information for admin panel'))},
        ),
        migrations.AlterField(
            model_name='profile',
            name='access_card',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='NTNU Adgangskort (EMXXXXXXXXXX)'),
        ),
    ]
