# Generated by Django 2.2.1 on 2019-05-19 09:51

import applications.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0020_auto_20190507_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Ditt telefonnummer vil kun vises for medlemmer av Hackerspace dersom du gjør en reservasjon av utstyr i tilfelle du må kontaktes.', max_length=8, null=True, validators=[applications.validators.validate_phone_number], verbose_name='Telefonnummer'),
        ),
    ]
