# Generated by Django 3.0.2 on 2020-02-05 20:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0022_auto_20190519_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsOfService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publiseringsdato')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tos_accepted',
        ),
        migrations.AddField(
            model_name='profile',
            name='accepted_tos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userprofile.TermsOfService', verbose_name='Seneste aksepterte TOS'),
        ),
    ]
