# Generated by Django 3.0.2 on 2020-02-05 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0023_auto_20200205_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tos_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
