# Generated by Django 3.0.2 on 2020-02-05 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0024_profile_tos_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tos_accepted',
        ),
    ]
