# Generated by Django 3.0.2 on 2020-02-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0026_auto_20200211_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsofservice',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
