# Generated by Django 3.0.2 on 2020-03-04 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_image_compressed'),
        ('userprofile', '0029_auto_20200304_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('category', models.ManyToManyField(to='userprofile.Category')),
                ('prerequisites', models.ManyToManyField(blank=True, to='userprofile.Skill')),
                ('thumb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.Image')),
            ],
        ),
    ]
