# Generated by Django 3.0.2 on 2020-03-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0032_auto_20200304_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color_hex',
            field=models.CharField(default='#212121', max_length=7),
        ),
    ]
