# Generated by Django 3.0.2 on 2020-03-04 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0033_category_color_hex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='color_hex',
        ),
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='hs-green', max_length=7),
        ),
    ]
