# Generated by Django 3.0.2 on 2020-03-04 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0034_auto_20200304_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='hs-green', max_length=20),
        ),
    ]
