# Generated by Django 3.0.2 on 2020-03-04 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0035_auto_20200304_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='', max_length=20),
        ),
    ]
