# Generated by Django 3.0.2 on 2020-03-11 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0038_auto_20200311_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='category',
            new_name='categories',
        ),
    ]
