# Generated by Django 3.0.2 on 2020-03-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0039_auto_20200311_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='', max_length=20),
        ),
    ]
