# Generated by Django 3.1.2 on 2021-04-28 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0040_auto_20200315_1428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('is_active_member', 'Is an active member. Catchall permission'), ('can_view_social', 'Can see social fields on UserProfile'), ('can_view_admin', 'Can see information for admin panel'))},
        ),
    ]
