# Generated by Django 3.1.1 on 2021-10-08 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0041_auto_20210428_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='access_card',
        ),
    ]
