# Generated by Django 3.2.12 on 2022-02-23 18:46

import applications.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0042_remove_profile_access_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Brukes til reservasjonssystem i tilfelle du må kontaktes.', max_length=15, null=True, validators=[applications.validators.validate_phone_number], verbose_name='Telefonnummer'),
        ),
    ]
