# Generated by Django 3.2.13 on 2023-02-20 18:00

import applications.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0043_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Brukes til reservasjonssystem i tilfelle du må kontaktes.', max_length=20, null=True, validators=[applications.validators.validate_phone_number], verbose_name='Telefonnummer'),
        ),
    ]
