# Generated by Django 5.0.3 on 2024-03-16 17:47

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0044_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsofservice',
            name='text',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
