# Generated by Django 3.1.7 on 2021-10-13 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0012_auto_20210210_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('body', models.TextField()),
                ('thumbnail_dark_text', models.BooleanField(default=False)),
                ('thumbnail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.image')),
            ],
        ),
    ]
