# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-03 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=100, verbose_name='Description')),
                ('tags', models.CharField(max_length=100, verbose_name='Tags')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.FileField(upload_to='images')),
                ('number', models.IntegerField(default=0)),
            ],
        ),
    ]
