# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-21 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20180623_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumb',
            field=models.ImageField(null=True, upload_to='thumbnails'),
        ),
    ]
