# Generated by Django 2.0.10 on 2019-05-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_image_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='compressed',
            field=models.ImageField(null=True, upload_to='compressed'),
        ),
    ]
