# Generated by Django 3.1.2 on 2020-10-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_image_compressed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True, max_length=100, verbose_name='Beskrivelse'),
        ),
        migrations.AlterField(
            model_name='image',
            name='tags',
            field=models.CharField(max_length=100, verbose_name='Tag/kategori'),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Tittel'),
        ),
    ]
