# Generated by Django 3.1.2 on 2020-10-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_auto_20201022_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='tags',
            field=models.CharField(default='Usortert', max_length=100, verbose_name='Tag/kategori'),
        ),
    ]
