# Generated by Django 3.1.2 on 2020-10-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_auto_20201026_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Kategorinavn')),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='tags',
        ),
    ]
