# Generated by Django 3.1.2 on 2020-10-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_image_img_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecategory',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Kategorinavn'),
        ),
    ]
