# Generated by Django 3.1.2 on 2020-10-26 19:07
# changed by hand very shortly after

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_image_img_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='description',
        ),
    ]
