# Generated by Django 3.1.2 on 2020-11-02 19:15

from django.db import migrations, models
import django.db.models.deletion
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_remove_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecategory',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Kategori'),
        ),
    ]
