# Generated by Django 3.0.2 on 2020-11-02 17:10

from django.db import migrations, models
import django.db.models.deletion
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_remove_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecategory',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='image',
            name='img_category',
            field=models.ForeignKey(default=files.models.get_default_category, on_delete=django.db.models.deletion.CASCADE, to='files.FileCategory', verbose_name='Kategori'),
        ),
    ]
