# Generated by Django 3.1.1 on 2021-01-27 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0010_auto_20201102_1915'),
        ('files', '0010_auto_20201102_1710'),
    ]

    operations = [
    ]
