# Generated by Django 3.1.6 on 2021-02-10 17:25

from django.db import migrations, models
import django.db.models.deletion
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0011_merge_20210127_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img_category',
            field=models.ForeignKey(default=files.models.get_default_category, on_delete=django.db.models.deletion.SET_DEFAULT, to='files.filecategory', verbose_name='Kategori'),
        ),
    ]
