# Generated by Django 3.1.2 on 2020-10-26 18:55

from django.db import migrations, models
import django.db.models.deletion
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0013_auto_20201026_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecategory',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='image',
            name='img_category',
            field=models.ForeignKey(default=files.models.get_default_category, on_delete=django.db.models.deletion.CASCADE, to='files.filecategory', verbose_name='Kategori'),
        ),
    ]
