# Generated by Django 3.1.2 on 2020-10-26 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0014_auto_20201026_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='files.filecategory', verbose_name='Kategori'),
        ),
    ]
