# Generated by Django 3.1.2 on 2020-10-26 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0015_auto_20201026_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='description',
        ),
    ]
