# Generated by Django 2.0.9 on 2018-11-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, verbose_name='navn')),
                ('startDate', models.DateTimeField(verbose_name='startdato')),
                ('endDate', models.DateTimeField(verbose_name='sluttdato')),
                ('manualOverride', models.BooleanField()),
            ],
        ),
    ]
