# Generated by Django 3.1.7 on 2022-01-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Jul, Påske etc.', max_length=50, verbose_name='navn')),
                ('logo', models.ImageField(blank=True, help_text='Dersom ingen logo lastes opp brukes standard hackerspace-logo', null=True, upload_to='seasonal_events/logos/')),
                ('start_date', models.DateTimeField(help_text='Prøv å unngå overlapp mellom datoer', verbose_name='startdato')),
                ('end_date', models.DateTimeField(help_text='Prøv å unngå overlapp mellom datoer', verbose_name='sluttdato')),
                ('active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('repeating', models.BooleanField(default=False, help_text='Repeteres hvert år', verbose_name='repeterende')),
                ('manual_override', models.BooleanField(help_text='Tving sesongen til å være aktiv', verbose_name='Manuel overskriving')),
                ('disable_reservations', models.BooleanField(help_text='Skru av mulighet for reservasjoner til ikke-medlemmer når denne sesongen er aktiv.', verbose_name='Hindre reservasjoner')),
            ],
            options={
                'verbose_name_plural': 'Seasons',
            },
        ),
    ]
