# Generated by Django 2.0.9 on 2018-11-21 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seasonal_events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='endDate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='season',
            old_name='manualOverride',
            new_name='manual_override',
        ),
        migrations.RenameField(
            model_name='season',
            old_name='startDate',
            new_name='start_date',
        ),
    ]
