# Generated by Django 2.0.9 on 2019-01-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasonal_events', '0002_auto_20181121_1958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'verbose_name_plural': 'Seasons'},
        ),
        migrations.AddField(
            model_name='season',
            name='repeating',
            field=models.BooleanField(default=False, verbose_name='repeterende'),
        ),
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.CharField(max_length=50, verbose_name='navn'),
        ),
    ]
