# Generated by Django 2.0.9 on 2019-03-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasonal_events', '0003_auto_20190122_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='header_name',
            field=models.CharField(default='', max_length=50, verbose_name='headernavn'),
        ),
    ]
