# Generated by Django 2.0.9 on 2019-03-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasonal_events', '0004_season_header_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='active',
            field=models.BooleanField(default=True, verbose_name='aktiv'),
        ),
    ]
