# Generated by Django 2.0.9 on 2019-03-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasonal_events', '0005_season_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='header_name',
        ),
        migrations.AddField(
            model_name='season',
            name='logo',
            field=models.ImageField(default='/website/img/logo/Hackerspace_huge.png', upload_to='seasonal_events/logos/'),
        ),
        migrations.AlterField(
            model_name='season',
            name='end_date',
            field=models.DateTimeField(help_text='Prøv å unngå overlapp mellom datoer', verbose_name='sluttdato'),
        ),
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.CharField(help_text='Jul, Påske etc.', max_length=50, verbose_name='navn'),
        ),
        migrations.AlterField(
            model_name='season',
            name='repeating',
            field=models.BooleanField(default=False, help_text='Repeteres hvert år', verbose_name='repeterende'),
        ),
        migrations.AlterField(
            model_name='season',
            name='start_date',
            field=models.DateTimeField(help_text='Prøv å unngå overlapp mellom datoer', verbose_name='startdato'),
        ),
    ]
