# Generated by Django 2.0.9 on 2019-03-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasonal_events', '0006_auto_20190318_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='logo',
            field=models.ImageField(default='static/website/img/logo/Hackerspace_huge.png', help_text='Dersom ingen logo defineres brukes standard hackerspace-logo', upload_to='seasonal_events/logos/'),
        ),
        migrations.AlterField(
            model_name='season',
            name='manual_override',
            field=models.BooleanField(verbose_name='Manuel overskriving'),
        ),
    ]
