# Generated by Django 2.0.10 on 2019-04-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasonal_events', '0009_auto_20190430_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='banner_color',
            field=models.CharField(blank=True, help_text='Tar en CSS klasse til bakgrunnsfarge. Dette kan være for eksempel hs-green, hs-yellow, hs-red, etc.', max_length=50, null=True, verbose_name='bannertext'),
        ),
        migrations.AlterField(
            model_name='season',
            name='banner_text',
            field=models.CharField(blank=True, help_text='Tekst som vil vises i en banner på forsiden.', max_length=220, null=True, verbose_name='bannertext'),
        ),
    ]
