# Generated by Django 2.0.10 on 2019-04-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasonal_events', '0011_auto_20190430_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='logo',
            field=models.ImageField(default='static/website/img/logo/hackerspace.svg', help_text='Dersom ingen logo defineres brukes standard hackerspace-logo', upload_to='seasonal_events/logos/'),
        ),
    ]
