# Generated by Django 2.2.1 on 2019-05-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasonal_events', '0013_auto_20190430_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='disable_reservations',
            field=models.BooleanField(default=False, help_text='Skru av mulighet for reservasjoner til ikke-medlemmer når denne sesongen er aktiv.', verbose_name='Hindre reservasjoner'),
            preserve_default=False,
        ),
    ]
