# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-03-06 17:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RaspberryPi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('last_seen', models.DateTimeField(verbose_name='last seen')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('mac', models.CharField(db_index=True, max_length=17, unique=True, validators=[django.core.validators.RegexValidator('^([a-f0-9]{2}:){5}[a-f0-9]{2}$')], verbose_name='MAC')),
            ],
        ),
    ]
