# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-24 18:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RaspberryPi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastSeen', models.DateTimeField(verbose_name='last seen')),
                ('ip', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(
                    '^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$')],
                                        verbose_name='IP')),
                ('mac', models.CharField(default='12:34:56:78:90:ab', max_length=17, validators=[
                    django.core.validators.RegexValidator('^([a-f0-9]{2}:){5}[a-f0-9]{2}$')], verbose_name='MAC')),
            ],
        ),
    ]
