# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-31 18:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rpi', '0002_auto_20170117_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaspberryPiAvailableNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='raspberrypi',
            name='ip',
            field=models.GenericIPAddressField(verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='raspberrypi',
            name='mac',
            field=models.CharField(db_index=True, max_length=17, unique=True,
                                   validators=[django.core.validators.RegexValidator('^([a-f0-9]{2}:){5}[a-f0-9]{2}$')],
                                   verbose_name='MAC'),
        ),
    ]
