# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-31 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('rpi', '0003_auto_20170131_1934'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RaspberryPiAvailableNames',
            new_name='RaspberryPiAvailableName',
        ),
    ]
