# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-31 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('rpi', '0004_auto_20170131_1946'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RaspberryPiAvailableName',
            new_name='Name',
        ),
    ]
